<a href="https://colab.research.google.com/github/rifka1/MSIBOrbit/blob/main/read_dataset_dari_github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

latihan

In [1]:
print('hello world')

hello world

In [3]:
!wget -O final_exam.csv https://raw.githubusercontent.com/rifka1/MSIBOrbit/main/Dataset/final_exam.csv

--2022-04-13 15:27:41--  https://raw.githubusercontent.com/rifka1/MSIBOrbit/main/Dataset/final_exam.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 740 [text/plain]
Saving to: ‘final_exam.csv’

final_exam.csv      100%[===================>]     740  --.-KB/s    in 0s

2022-04-13 15:27:41 (47.1 MB/s) - ‘final_exam.csv’ saved [740/740]

In [4]:
import pandas as pd
import numpy as np

In [6]:
dataset = pd.read_csv('https://raw.githubusercontent.com/rifka1/MSIBOrbit/main/Dataset/final_exam.csv', error_bad_lines = False)
dataset.keys()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

Index(['big_west', 'small_west', 'capital_city', 'big_east', 'small_east'], dtype='object')

In [7]:
dataset

    big_west  small_west  capital_city  big_east  small_east
0         87          77            86        71          70
1         75          83            90        82          76
2         80          73            87        85          81
3         75          82            85        89          85
4         91          71            85        72          75
5         89          87            96        79          75
6         91          77            95        79          75
7         87          84            89        85          72
8         90          86            93        84          72
9         94          93            91        86          75
10        82          83            96        85          90
11        91          94            94        76          83
12        83          79            91        71          80
13        86          92            85        82          85
14        84          72            77        72          80
15        82          86            96        78          80
16        88          76            84        78          78
17        89          84            87        76          86
18        94          85            91        74          83
19        87          93            83        77          77
20        89          87            90        74          76
21        88          89            81        70          75
22        75          89            79        80          81
23        85          77            95        89          74
24        81          92            93        80          84
25        78          73            95        89          75
26        93          86            90        77          75
27        88          87            91        88          80
28        84          93            78        75          80
29        90          95            91        78          75
30        91          90            88        82          70
31        88          84            80        72          80
32        82          82            95        77          90
33        94          82            94        81          86
34        83          93            90        75          70
35        91          72            78        78          85
36        76          85            89        75          80
37        80          90            90        87          72
38        76          81            90        76          90
39        90          90            95        81          90
40        88          78            81        89          63
41        84          83            90        82          82
42        70          70            70        70          70